config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'books#index'

  get 'books/index'

  devise_for :users
  mount RailsAdmin::Engine => '/command_center', as: 'rails_admin'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: authors
#
#  id         :bigint           not null, primary key
#  age        :integer
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Author < ApplicationRecord
  has_many :books

  validates :name, :age, presence: true
  validates :age, numericality: { only_integer: true,
                                  greater_than: 0 }
end

app/models/book.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: books
#
#  id          :bigint           not null, primary key
#  description :string
#  image_url   :string
#  title       :string
#  year        :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  author_id   :bigint           not null
#
class Book < ApplicationRecord
  belongs_to :author

  validates :title, :description, :year, presence: true
  validates :year, numericality: { only_integer: true,
                                   greater_than: 0 }
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  admin                  :boolean          default(FALSE), not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_accessor :special_code

  validates :email, :password, presence: true
  validates :email, uniqueness: true

  validate :valid_special_code?, if: proc { admin }

  private

  def valid_special_code?
    return if special_code == '4DM1N_4C3SS'

    errors.add(:special_code)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[admin special_code])
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :load_authors, only: :index

  def index
    @q = Book.ransack(params[:q])

    books = @q.result(distinct: true)
    @books_count = books.count

    @books = books.includes(:author)
                  .order(title: :asc)
                  .page(params[:page])
  end

  private

  def load_authors
    @authors = Author.all
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(
      :email, :password, :password_confirmation, :admin, :special_code
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/form_helper.rb
# frozen_string_literal: true

module FormHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
  end

  def form_group_for(form, field, opts = {}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
      concat form.label(field, class: 'control-label') if label
      concat capture(&block)
      concat errors_for(form, field)
    end
  end
end

app/views/books/_filters.html.slim
= search_form_for @q, url: books_index_path do |f|
  .col-sm-6.col-md-6
    = f.search_field :title_or_description_cont,
                      id: 'book-search',
                      class: 'form-control',
                      placeholder: 'Press Enter to search by book title or description'

  .col-sm-3.col-md-3
    = f.select :author_id_eq,
               options_from_collection_for_select( \
                 @authors, :id, :name, @q.author_id_eq \
               ),
               { include_blank: 'Select Author' },
               class: 'form-control'

  .col-sm-3.col-md-3
    .btn.btn-success[type="button"]
      = sort_link(@q, :title, 'Book title', default_order: :desc)

    =< link_to root_path, class: 'btn btn-danger' do
      i.fas.fa-times

app/views/books/index.html.slim
.container
  .well.well-md.col-sm-12.col-md-12
    .col-sm-10.col-md-10.form-outline
      = render 'filters'

    .col-sm-1.col-md-1
      = link_to 'Dashboard', rails_admin_path, class: 'btn btn-primary'

  - if @books.any?
    h5
      strong = "#{@books_count} books found."

    #books.row.row-cols-1.row-cols-md-4.g-3
      - @books.each do |book|
        .book-item.col
          .card.h-100
            img[alt="great book" src="#{book.image_url}" style="height: 160px"]

            .card-body
              h5.card-title
                strong = "#{book.title} (##{book.id})"
              p.card-text = book.description

            .card-footer
              small.text-muted = "Published in #{book.year} by #{book.author.name}"

    .text-center
      = paginate @books

  - else
    h5
      strong = "No books were found."

app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZygoRailsChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>